name: S3 Databse Deploy
on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Download Databse
        run: curl -O https://data.fcc.gov/download/pub/uls/complete/l_amat.zip
      - name: Process Database
        run: unzip l_amat.zip && mkdir data && mv HD.dat ./data && mv EN.dat ./data
      - name: Deploy Database Files
        uses: reggionick/s3-deploy@v4
        with:
          folder: data
          bucket: database.hamradiowallet.com
          bucket-region: ${{ secrets.AWS_REGION }}
          private: false
